name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install libvips
      run: sudo apt-get update && sudo apt-get install -y libvips-dev
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
